DjangoDjangoDjango - Improving/PostIT/PostIT/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page3.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoDjangoDjango - Improving/PostIT/page3/urls.py
from unicodedata import name
from django.urls import path
from . import views
# from .views import HomeView

urlpatterns = [
    #     path('', views.home, name='home-page'),
    path('', views.home_timeline, name='home-page'),
    path('', views.home_timeline, name='expanded-post-page'),
    path('upload_reply/<int:pk>',
         views.upload_reply, name='upload_reply'),

    #     path('post/<int:post_id>', views.post_details, name='post-page'),
    path('add_post', views.add_post, name='add-post'),
    path('add_image_post', views.add_image_post, name="add-image-post"),
    path('add_video_post', views.add_video_post, name="add-video-post"),
    path('post/edit/<int:post_id>', views.edit_post, name='edit-post'),
    path('post/edit_images/<int:post_id>',
         views.edit_image_post, name='edit-image-post'),
    path('post/edit_video/<int:post_id>',
         views.edit_video_post, name='edit-video-post'),
    path('post/delete/<int:post_id>', views.delete_post, name='delete-post'),
    path('category/<str:cat>/', views.category, name='posts-by-category'),
    # path('like/', views.like_post, name='like-post'),
    # path('like/<int:pk>', views.like_post_details, name='like-post-details'),
    path('like/', views.like, name='like'),
    path('setLikes/', views.set_likes, name='set_likes'),
    path('updateSession/', views.update_session, name='update_session'),
    path('getSessionData/', views.get_session_data, name='get_session_data'),

    path('fetch_replies_to_reply/', views.fetch_replies_to_reply,
         name='fetch_replies_to_reply'),
    # REST API views
    path('posts', views.post_list_view, name='post-list-view'),
    #     path('', views.home_view, name='home-page'),
    path('getPosts/', views.getPosts, name='get-posts-rest'),
    path('getPosts/<int:pk>', views.getPost, name='get-post-rest'),
    path('getPosts/<int:pk>/update', views.updatePost, name='update-post-rest'),
    path('getPosts/<int:pk>/delete', views.deletePost, name='delete-post-rest'),


    path('posts/<str:user>', views.posts_by_user, name="posts-by-user"),
    path('create_gamer_profile/<str:user>',
         views.create_game_profile, name="create-gamer-profile"),
    path('matchmaking/<str:user>', views.MatchmakingHome, name="matchmaking-home"),
]

DjangoDjangoDjango - Improving/PostIT/page3/models.py
from email.policy import default
from random import choices
from secrets import choice
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import int_list_validator
from django.contrib.postgres.fields import ArrayField
from datetime import datetime, date
from ckeditor.fields import RichTextField


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    tags = models.CharField(
        max_length=255, default='none')

    def save(self, *args, **kwargs):
        self.tags = self.name.replace(' ', '-').lower()
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('home-page')


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    bio = models.TextField()
    profile_pic = models.ImageField(
        null=True, blank=True, upload_to="images/profile")
    discord_link = models.CharField(max_length=255, null=True, blank=True)
    twitch_link = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return str(self.user)


class Post(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    body = RichTextField(blank=True, null=True)
    # body = models.TextField()
    reply_to = models.IntegerField(null=True, blank=True, default=-1)
    is_reply = models.BooleanField(null=True, default=False, blank=True)
    is_parent_a_reply = models.BooleanField(
        null=True, default=False, blank=True)
    reply_root = models.IntegerField(null=True, blank=True, default=-1)
    post_date = models.DateField(auto_now_add=True)
    post_datetime = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=50, default='none')
    tags = models.CharField(
        max_length=255, default='none')
    likes = models.ManyToManyField(
        User, default=None, blank=True, related_name='posts')
    like_count = models.BigIntegerField(default='0')
    reply_count = models.BigIntegerField(default='0')
    video = models.FileField(null=True, blank=True, upload_to="videos/")
    has_images = models.BooleanField(null=True, blank=True, default=False)
    has_video = models.BooleanField(null=True, blank=True, default=False)
    user_profile = models.ForeignKey(
        Profile, on_delete=models.DO_NOTHING, default=None, null=True, blank=True,)
    body = RichTextField(blank=True, null=True)

    def liked_by(self):
        likers = []
        for a in self.likes.all():
            likers.append(a.username)
        return likers

        return ', '.join([a.username for a in self.likes.all()])
        return self.likes.all()

    @property
    def num_likes(self):
        return self.likes.all().count()

    def total_likes(self):
        return self.likes.count()

    def save(self, *args, **kwargs):
        self.tags = self.category.replace(' ', '-').lower()
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.body + ' | ' + str(self.author) + '| ' + str(self.id) + ' | ' + str(self.is_reply)

    def get_absolute_url(self):
        return reverse('post-page', args=(str(self.post_id)))


class Replies(models.Model):
    reply_to_post = models.ForeignKey(
        Post, on_delete=models.CASCADE, null=True, blank=True)
    reply_to = models.IntegerField(null=True, blank=True, default=-1)
    post_id = models.IntegerField(null=True, blank=True, default=-1)
    reply_root = models.IntegerField(null=True, blank=True, default=-1)

    def __str__(self):
        return 'Reply to: ' + str(self.reply_to) + ' | ' + 'Post id: ' + str(self.post_id) + ' | ' + 'reply root: ' + str(self.reply_root)


class ImageFiles(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, null=True, blank=True)
    image = models.FileField(null=True, blank=True, upload_to='images/')


LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)


class GameProfile(models.Model):
    games_list = [('Val', 'Valorant'), ('COD', 'Call of Duty'),
                  ('LOL', 'League of Legends'), ('CS Go', 'Counter Shit: GO')]

    class ValorantServers(models.TextChoices):
        APAC = 'APAC', 'Asia Pacific'
        EMEA = 'EMEA', 'Europe'
        NA = 'NA', 'North America(meaning shit)'
        JA = 'JA', 'Japan'

    class CODServers(models.TextChoices):
        APAC = 'APAC', 'Asia Pacific'
        EMEA = 'EMEA', 'Europe'
        NA = 'NA', 'North America(meaning shit)'

    class LOLServers(models.TextChoices):
        APAC = 'APAC', 'Asia Pacific'
        EMEA = 'EMEA', 'Europe'
        NA = 'NA', 'North America(meaning shit)'

    class CSServers(models.TextChoices):
        EMEA = 'EMEA', 'Europe'
        NA = 'NA', 'North America(meaning shit)'

    class ValorantRanks(models.TextChoices):
        Iron = 'IRON', 'Iron :((('
        Bronze = 'Bronze', 'Bronze :(('
        Silver = 'Silver', 'Silver :('
        Gold = 'Gold', 'Gold :('
        Platinum = 'Platinum', 'Platinum '
        Diamond = 'Diamond', 'Diamond :) '
        Asencdant = 'Asencdant', 'Asencdant :)) '
        Immortal = 'Immortal', 'Immortal >_< '
        Radiant = 'Radiant', 'Radiant :> '

    class LOLRanks(models.TextChoices):
        Iron = 'IRON', 'Iron :((('
        Bronze = 'Bronze', 'Bronze :(('
        Silver = 'Silver', 'Silver :('
        Gold = 'Gold', 'Gold :('
        Platinum = 'Platinum', 'Platinum '
        Diamond = 'Diamond', 'Diamond :) '
        Master = 'Master', 'Master :)) '
        Grandmaster = 'Grandmaster', 'Grandmaster >_< '
        Challenger = 'Challenger', 'Challenger :> '

    class CODRanks(models.TextChoices):
        Rookie = 'Rookie', 'Rookie :((('
        Veteran = 'Veteran', 'Veteran :(('
        Elite = 'Elite', 'Elite :('
        Pro = 'Pro', 'Pro :('
        Master = 'Master', 'Master '
        Grandmaster = 'Grandmaster', 'Grandmaster :) '
        Legendary = 'Legendary', 'Legendary :)) '

    class CSRanks(models.TextChoices):

        Silver = 'Silver', 'Silver :('
        Gold = 'Gold', 'Gold :('
        Master_Guardian = 'Master Guardian', 'Master Guardian '
        Distinguished_Master_Guardian = 'Distinguished Master Guardian', 'Distinguished Master Guardian :) '
        Legendary = 'Legendary', 'Legendary :)) '
        Elite = 'Elite', 'Elite >_< '

    servers_list = [('Val', ValorantServers.choices), ('COD', CODServers.choices),
                    ('LOL', LOLServers.choices), ('CS', CSServers.choices)]

    ranks_list = [('Val', ValorantRanks.choices), ('COD', CODRanks.choices),
                  ('LOL', LOLRanks.choices), ('CS', CSRanks.choices)]

    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    game = models.CharField(max_length=50, choices=games_list)
    server = models.CharField(max_length=50, choices=servers_list)
    rank = models.CharField(max_length=50, choices=ranks_list, default="")

    def __str__(self):
        return str(self.user) + " | " + str(self.game) + " | " + str(self.server) + " | " + str(self.rank)

DjangoDjangoDjango - Improving/PostIT/page3/forms.py
from dataclasses import fields
from email.mime import image
from django.forms import ModelForm
from matplotlib import widgets
from .models import Post, Category, ImageFiles, GameProfile
from django import forms


# choices = [('VALORANT', 'VALORANT'), ('CSGO', 'CSGO'), ('COD', 'COD')]
choices = Category.objects.all().values_list('name', 'name')
tags = Category.objects.all().values_list('tags', 'tags')
choice_list = []

for item in choices:
    choice_list.append(item)


class PostForm(ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        fields = ('title', 'body', 'category')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}),
            # 'author': forms.TextInput(attrs={'class': 'form-control', 'value': '', 'id': 'author-name', 'type': 'hidden'}),
            # 'author': forms.Select(attrs={'class': 'form-control'}),
            'category': forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write something here...'})
        }


class PostImageForm(ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        fields = ('title', 'body', 'category')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}),
            'category': forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write something here...'})
        }


class PostVideoForm(ModelForm):
    class Meta:
        model = Post
        # fields = '__all__'
        fields = ('title', 'body', 'category', 'video')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}),
            # 'author': forms.TextInput(attrs={'class': 'form-control', 'value': '', 'id': 'author-name', 'type': 'hidden'}),
            # 'author': forms.Select(attrs={'class': 'form-control'}),
            'category': forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write something here...'})
        }


class EditPostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body', 'category')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Post Title'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write something here...'}),
            'category': forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
        }


class EditVideoPostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body', 'category', 'video')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Post Title'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write something here...'}),
            'category': forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
        }


class EditImagePostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body', 'category')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Post Title'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write something here...'}),
            'category': forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
        }


class ImageForm(ModelForm):
    image = forms.ImageField(
        label="Image", widget=forms.ClearableFileInput(attrs={"multiple": True}), required=False)

    class Meta:
        model = ImageFiles
        fields = ("image",)


class GameProfileForm(ModelForm):
    class Meta:
        model = GameProfile
        # fields = '__all__'
        fields = ('game', 'server', 'rank')
        # widgets = {
        #     'game': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Valorant'}),
        #     # 'author': forms.TextInput(attrs={'class': 'form-control', 'value': '', 'id': 'author-name', 'type': 'hidden'}),
        #     # 'author': forms.Select(attrs={'class': 'form-control'}),
        #     'category': forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
        #     'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write something here...'})
        # }
class MatchmakingForm(ModelForm):
    class Meta:
        model=GameProfile
        fields = ('game', 'server', 'rank')

DjangoDjangoDjango - Improving/PostIT/page3/templates/add_new_reply.html
{% extends 'base.html' %}
{% block title %}
Page3 - Add new reply
{% endblock title %}

{% block content %}
<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown"
        aria-expanded="false">
        Dropdown button
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li><a class="dropdown-item" href="#">Action</a></li>
        <li><a class="dropdown-item" href="#">Another action</a></li>
        <li><a class="dropdown-item" href="#">Something else here</a></li>
    </ul>
</div>
{% endblock content %}

DjangoDjangoDjango - Improving/PostIT/page3/templates/add_post.html
{% extends 'base.html' %}
{% block title %}
Page3 - Add post
{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}
{% if user.is_authenticated %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button type="submit">Post</button>
</form>


{% else %}
Login first!
{% endif %}
{% endblock content %}

DjangoDjangoDjango - Improving/PostIT/page3/templates/add_reply.html
{% extends 'base.html' %}
{% block title %}
Page3 - Add reply
{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}



{% if user.is_authenticated %}

<a href="{% url 'add-image-reply' pk %}">Image Reply</a>
<a href="{% url 'add-video-reply' pk %}">Video Reply</a>

{% if replying_to %}
Replying to
{% for parent in replying_to %}
{{ parent.author}}<br />
{{ parent.body|safe }}
<br /><br />
{% endfor %}
{% endif %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}

    <button type="submit">Reply</button>
</form>


{% else %}
Login first!
{% endif %}
{% endblock content %}

DjangoDjangoDjango - Improving/PostIT/page3/templates/add_video_post.html
{% extends 'base.html' %}
{% block title %}
Page3 - Add Video Post
{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}
{% if user.is_authenticated %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button type="submit">Post</button>
</form>


{% else %}
Login first!
{% endif %}
{% endblock content %}

DjangoDjangoDjango - Improving/PostIT/page3/templates/matchmaking.html
{% extends 'base.html' %}
{% block title %}
Create Gamer Profile
{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}
{% if user.is_authenticated %}
<form action="" method="POST" enctype="multipart/form-data">
    <h1>Start Matchmaking</h1>
    {% csrf_token %}
    <p>Enter Preferred Game</p>
    {{form.game}}
    <hr />
    <p>Enter Preferred Server</p>
    {{form.server}}
    <hr />
    <p>Enter Preferred Rank to pair with</p>
    {{form.rank}}

    {{user.username}}
    <button type="submit">Create</button>
</form>
{{game_profiles}}

{%if game_profiles%}
    <div class="gamer_profiles">
        {%for g in game_profiles%}
        <div>{{g.user}}</div>
        <div>{{g.game}}</div>
        <div>{{g.rank}}</div>
        <hr>
        {%endfor%}
    </div>
{%endif%}

{% else %}
Login first!
{% endif %}
{% endblock content %}

DjangoDjangoDjango - Improving/PostIT/page3/templates/replies_page.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Page3 - Add reply
{% endblock title %}

{% block content %}
{% load crispy_forms_tags %}



<div class="main-body">
    <div class="page-contents">
        <div class="sidebar" style="visibility: hidden !important;"></div>
        <div class="posts-timeline">
            <div class="post">



                <section class="post-top-part">
                    <div class="profile-pic">
                        {%if post.user_profile.profile_pic.name %}
                        <img src="{{ post.user_profile.profile_pic.url }}" width="500">
                        {% endif %}
                        <!-- <img src="{{ post.user_profile.profile_pic.url }}" width="500"> -->
                    </div>

                    <span class="author-date">{{post.author}} <span class="date">
                            {{post.post_date}}
                        </span> </span>
                </section>

                {% if user.is_authenticated %}
                Logged in as: {{user}} | {{user.id}}
                {% if user.id == post.author.id %}
                <h1>{{ post.title }}</h1><a href="{% url 'edit-post' post.pk %}">Edit</a><br />
                {% endif %}
                {% endif %}


                <small>{{ post.author.username }}
                    {{ post.post_date}} | {{post.pk}}</small><br />
                <hr>
                {{post.body}}
                <br />
                {% if post.has_images %}

                {% for image in image_list %}
                {% if image.post.id == post.id %}
                <img src="{{ image.image.url}}" width="500">
                {% endif %}
                {% endfor %}
                {{ post.imagefiles}}
                {% endif %}

                {% if post.video %}
                <video width="500" controls autoplay>
                    <source src="{{post.video.url}}" type="video/mp4">
                </video>

                {% endif %}
                <br />
                {% if user.is_authenticated %}

                <!-- Modal start -->

                <div class="reply-modal-container" id="reply-modal-container">
                    <div class="modal-div">
                        <h1>reply to</h1>
                        {% include 'post_replies_form.html' %}
                        <button id="close-modal">CLose modal</button>
                    </div>
                </div>

                <!-- Modal end -->


                {% if user.profile.id %}
                <!-- <span id="like_count" type="hidden">{{ post.like_count}}</span> -->
                <button id="like-button" class="like-button" name="{{ post.like_count }}" value="{{ post.pk }}">LIKED BY
                    {{post.like_count}}</button>



                <button id="open-reply-modal" value="{{post.pk}}">Reply</button>
                {% endif %}

                {% endif %}

            </div>
            <div id="replies-section">
                {% include 'replies_list.html' %}
            </div>
        </div>
    </div>
</div>

<!-- JS Scripts Here -->

<script>
    function updateText(btn, no_of_likes) {
        btn.text("LIKED BY" + " " + no_of_likes)
    }
    $(document).on('click', '#like-button', function (e) {
        e.preventDefault();

        var this_ = $(this)
        postid = this_.attr("value").valueOf()



        $.ajax({
            type: 'POST',
            url: '{% url "like" %}',
            data: {
                postid: postid,
                // postid: $('#like-button').val(),
                action: 'post',
            },
            success: function (json) {
                no_of_likes = json['result'];
                console.log(json)
                updateText(this_, no_of_likes)
            },
            error: function (xhr, errmsg, err) {

            }
        });
    })


</script>

<script>
    function updateText(btn, no_of_likes) {
        btn.text("LIKED BY" + " " + no_of_likes)
    }
    function updateLikes() {

        let allLikes = document.getElementsByClassName('like-button');


        for (let i = 0; i < allLikes.length; i++) {
            let attributeValue = allLikes[i].getAttribute('value');
            console.log(typeof allLikes[i])
            console.log(attributeValue)

            $.ajax({
                type: 'POST',
                url: '{% url "set_likes" %}',
                data: {
                    postid: attributeValue,
                    // postid: $('#like-button').val(),
                    action: 'post',
                    // postid: '{{ post.pk }}',
                },
                success: function (json) {
                    no_of_likes = json['result'];
                    //console.log(json)
                    //updateText(allLikes[i], no_of_likes)
                    allLikes[i].innerHTML = "LIKED BY" + " " + no_of_likes
                    console.log("AJAX REQUEST")
                },
                error: function (response) {

                }
            });


        }
        console.log(allLikes)

    }

    const xhr = new XMLHttpRequest()
    const method = 'GET'
    const url = "/posts"
    const responseType = 'json'

    xhr.responseType = responseType
    xhr.open(method, url)
    xhr.onload = function () {
        var listedItems = xhr.response.response
        console.log(listedItems)
    }
</script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
    // form upload

    const modalContainer = document.getElementById("reply-modal-container");
    const close = document.getElementById("close-modal");


    $(document).on('click', '#open-reply-modal', function (e) {
        var this_ = $(this);
        postid = this_.attr("value").valueOf();
        console.log("POSTID: " + postid)
        modalContainer.classList.add('show');
    });




    close.addEventListener('click', () => {
        modalContainer.classList.remove('show');
    });


    $('#id_ajax_upload_form').submit(function (e) {
        e.preventDefault();
        $form = $(this)
        var formData = new FormData(this);

        //var this_ = $(this)
        //postid = this_.attr("value").valueOf()
        formData.append('postid', postid)
        $.ajax({
            url: window.location.pathname,
            type: 'POST',
            data: formData,

            success: function (response) {
                //alert("JKJJK")
                $("#replies-section").html(response['replies_list']);
                $("#id_title").val('');
                $("#id_body").val('');
                $("#id_image").val('');
                //console.log($("#id_image").val())
                //$("#id_category").val('');
                modalContainer.classList.remove('show');
            },
            cache: false,
            contentType: false,
            processData: false
        });
    });

    $('#id_ajax_upload_form2').submit(function (e) {
        e.preventDefault();
        $form = $(this)
        var formData = new FormData(this);
        //var this_ = $(this)
        //postid = this_.attr("value").valueOf()
        formData.append('postid', postid)
        $.ajax({
            url: window.location.pathname,
            type: 'POST',
            data: formData,
            success: function (response) {
                //alert("JKJJK")
                $("#replies-section").html(response['replies_list']);
                $("#id_title").val('');
                $("#id_body").val('');
                $("#id_video").val('');
                //console.log($("#id_image").val())
                //$("#id_category").val('');
                modalContainer.classList.remove('show');
            },
            cache: false,
            contentType: false,
            processData: false
        });
    });
    // end
</script>

<script>
    window.addEventListener("pageshow", hideVidForm);

    function hideVidForm() {
        document.getElementById("vid-form").style.display = 'none';
    }


    document.getElementById('toggle-media-type').addEventListener('click', function () {
        let elem = document.getElementById('toggle-media-type');
        form1 = document.getElementById("img-form")
        form2 = document.getElementById("vid-form")
        if (elem.innerHTML == "Add video") {
            elem.innerHTML = "Add images";

            form1.style.display = 'none';
            form2.style.display = 'block';
        }
        else {
            elem.innerHTML = "Add video";
            form1.style.display = 'block';
            form2.style.display = 'none';
        }

    })
</script>

<script>
    $(document).on('click', '#show-replies', function (e) {
        e.preventDefault();

        var this_ = $(this)
        postid = this_.attr("value").valueOf()



        $.ajax({
            type: 'POST',
            url: '{% url "fetch_replies_to_reply" %}',
            data: {
                postid: postid,
                // postid: $('#like-button').val(),
                action: 'post',
            },
            success: function (json) {

                console.log(json['replies_list'])
                let repliesHolders = document.getElementsByClassName('replies-holder');
                for (let i = 0; i < repliesHolders.length; i++) {
                    let attributeValue = repliesHolders[i].getAttribute('value');
                    console.log(typeof repliesHolders[i])
                    console.log(typeof attributeValue)
                    console.log(attributeValue)
                    if (postid === attributeValue) {
                        console.log("This one!")
                        let elem = repliesHolders[i];
                        var child = elem.lastElementChild;
                        while (child) {
                            elem.removeChild(child);
                            child = elem.lastElementChild;
                        }
                        //var repliesList = document.createElement("div")
                        //repliesList.id = "replies-div"
                        //$("#replies-div").innerHTML = "Yahallo"
                        //console.log($('#replies-div').text())
                        elem = repliesHolders[i]
                        var id = 'replyTo' + postid

                        elem.setAttribute('id', id)

                        $("#" + id).html(json['replies_list'])

                        var div = document.getElementById(id)
                        console.log("DIVV:", div)
                        if (div.style.display === "none") {
                            div.style.display = "block"
                            console.log("THIS: ", this_)
                            console.log()

                        }
                        else {
                            div.style.display = "none"
                        }


                        //elem.html(json['replies_list']);

                        //$("#replies-holder").html(json['replies_list']);
                        //repliesList.html(json['replies_list'])
                        //elem.appendChild(repliesList)

                    }
                }

            },
            error: function (xhr, errmsg, err) {

            }
        });
    });
</script>

<script>
    function toggleReplies(e) {


        if (e.includes("Show")) {
            return e.replace("Show", "Hide")
        }
        else {
            return e.replace("Hide", "Show")
        }
    }
</script>

{% endblock content %}